export enum ActionType {
    CREATE_REQUEST= "CREATE_REQUEST",
    CREATE_ADDITION = "CREATE_ADDITION",
    CREATE_SUBSTRACTION = "CREATE_SUBSTRACTION",
    CREATE_MULTIPLICATION = "CREATE_MULTIPLICATION",
    CREATE_DIVISION = "CREATE_DIVISION",
}
