export enum ActionRoomsType {
  REQUEST_GET_ROOMS = 'REQUEST_GET_ROOMS',
  GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS',
  GET_ROOMS_FAILED = 'GET_ROOMS_FAILED',
  GET_SINGLE_ROOM_SUCCESS = 'GET_SINGLE_ROOM_SUCCESS'
}
